/* eslint-disable max-lines */

const en = {
  FirstAbuDhabiBank: "First Abu Dhabi Bank",
  how: "How do you want your egg today?",
  login: "Login",
  currency: "Currency",
  electronicBankingServices: "Electronic Banking Services",
  hello: "Hello",
  welcome: "Welcome !",
  middleName: "Middle Name",
  verification: "Verification",
  verNote:
    "Verify your credential by OTP sent to your mobile or email address.",
  confirm: "Confirm",
  fillNote: "Fill the fields with your data.",
  loremIpsum3: `Aliquam nibh magna, auctor sollicitudin ante tincidunt, pulvinar lobortis dolor. Ut lobortis, urna sit amet pellentesque aliquet, odio dolor sagittis tellus, in aliquet augue velit sed odio. Suspendisse vitae odio nibh. Pellentesque a cursus velit. Sed non scelerisque enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis sollicitudin mauris non tincidunt.
  `,
  loremIpsum2: ` Duis et arcu non lectus dapibus aliquam viverra id neque. Nulla ut tellus id lectus fringilla scelerisque quis ac diam. Aliquam elementum in neque ac pretium. Nam sit amet quam fermentum, congue libero non, sollicitudin risus. Praesent molestie, erat maximus pretium dapibus, augue risus facilisis nisi, molestie fringilla enim ante vel nibh. Aliquam metus lorem, imperdiet eu ultricies placerat, bibendum ac ipsum. Nulla vestibulum, nulla eu mattis fermentum, velit tortor sodales nulla, quis scelerisque nibh orci et nibh. Donec arcu metus, feugiat at venenatis ut, molestie at nisi. Aenean sit amet felis felis.`,
  loremIpsum: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mauris augue, rhoncus dapibus purus at, hendrerit ultrices magna. Mauris iaculis magna nec sagittis sodales. Etiam malesuada lectus at augue molestie faucibus vitae vitae est. Donec congue, ante vel sollicitudin placerat, lorem turpis viverra enim, vitae finibus lorem lectus non est. Nam vehicula dui urna, eget convallis massa tincidunt quis. Morbi sit amet gravida ante, sit amet placerat lorem. Aliquam erat volutpat. Nunc euismod est odio, ac egestas lectus gravida dictum.`,
  continue: "Continue",
  enterCorproateDetails: "Corporate Details",
  ContactNumber: "Contacts number",
  corporateId: "Corporate ID *",
  companyName: "Company Name",
  emirate: "Emirate",
  emailAddress: "Email Address *",
  office: "Office",
  customerId: "Customer ID *",
  mailingAddress: "Mailing Address *",
  contactPerson: "Contact Person",
  mobileNumber: "Mobile Number *",
  dailyLimit: "Corporate Daily Limit ",
  newCustomer: "New Customer",
  existingCustomer: "Existing Customer",
  accountDetails: "Account Details",
  accountSummary: "Account Summary ",
  addAccountDetails: "Add Account Details",
  addMoreAccounts: "Add More Accounts",
  noAccountsAdded: "No Accounts Added",
  noAccessAdded: "No Access Added",
  addAccountDesc: "Click on + Button to Add  FAB and Non-FAB Accounts",
  addAccounts: "Add Accounts",
  fabAccount: "FAB Account",
  nonFabAccount: "Non-FAB Account",
  typeOfAccount: "Type of account",
  name: "Name",
  accountNumber: "Account Number",
  saveAndContinue: "Save & Continue",
  moduleAccess: "Module Access",
  required: "Required",
  selectFabAccount: "Select are you New or Existing customer of FAB Bank.",
  bankName: "Bank Name",
  country: "Country",
  swift: "BIC/SWIFT",
  cardNumber: "Card Number",
  ibanAccountNumber: "IBAN / Account Number",

  // token type drop down
  softToken: "Soft Token",
  hardToken: "Hard Token",
  smsOtp: "SMS-OTP",
  tokenType: "Token Type",

  // module Dropdown
  payroll: "Payroll",
  ratibi: "Ratibi",
  rcd: "RCD",
  rcp: "RCP",
  hostToHost: "Host to Host",
  gpssa: "GPSSA",
  directDebit: "Direct Debit",
  mt101: "MT101",
  contactDetails: "Contact Details",
  mt940: "MT940",
  registration: "Registration",
  // product drop down
  payrollNonWPS: "Payroll (Non WPS)",
  payrollWPS: "Payroll (WPS)",
  trade: "trade",

  // currencies
  AED: "AED",
  USD: "USD",
  AUD: "AUD",
  BDT: "DBT",
  BHD: "BHD",
  CAD: "CAD",
  CHF: "CHF",
  DKK: "DKK",
  EGP: "EGP",
  EUR: "EUR",
  GBP: "GBP",
  HKD: "HKD",
  IDR: "IDR",
  INR: "INR",
  JOD: "JOD",
  JPY: "JPY",
  KWD: "KWD",
  LBP: "LBP",
  LKR: "LKR",
  MAD: "MAD",
  MYR: "MYR",
  NOK: "NOK",
  NZD: "NZD",
  OMR: "OMR",
  PHP: "PHP",
  PKR: "PKR",
  QAR: "QAR",
  SAR: "SAR",
  SDG: "SDG",
  SEK: "SEK",
  SGD: "SGD",
  SYP: "SYP",
  THB: "THB",
  YER: "YER",
  ZAR: "ZAR",
  authorisationRules: "Authorisation Rules",
  authorisationRulesDesc: "Set the number of approvers and limits.",
  sequentialApproval: "Sequential Approval",
  parallelApproval: "Parallel Approval",
  cancel: "Cancel",
  // module access
  proudct: "Product",
  account: "Account",
  role: "Role",
  limit: "Limit",
  accountServices: "Account Services",
  payments: "Payments",
  payrollServices: "Payroll Services",
  wps: "WPS*",
  salaryPayments: "Salary Payments (Non-WPS)*",
  ratibiServices: "Ratibi Services*",
  gpssPayment: "GPSS Payment*",
  tradeFacility: "Trade Facility",
  importLettersOfCredit: "Import Letters of Credit (ILC)",
  importCollections: "Import Collections (IC)",
  inwardAndOutwardGuarantees: "Inward and Outward Guarantees (IG/OG)",
  exportLettersOfCredit: "Export Letters of Credit (ELC)",
  exportCollections: "Export Collections (EC)",
  financingRequest: "Financing Request (FR)",
  otherServices: "Other Services",
  remoteChequeDeposit: "Remote Cheque Deposit (RCD)",
  remoteChequePrinting: "Remote Cheque Printing (RCP)",
  collectionsModule: "Collections Module",
  liquidity: "Liquidity (LMS)",
  reportDesigner: "Report Designer (IIR)",
  swiftMT101FundTransfer: "SWIFT MT101 Fund Transfer",
  addUserDetails: "Add User Details",
  validationCustomerId: "Must be 7 numbers",
  validationCorporateId: "Must be 16 characters or less",
  validationCompanyName: "Must be 60 characters or less",
  validationMailingAddress: "Must be 60 characters or less",
  validationEmirate: "Must be 30 characters or less",
  validationEmail: "Invalid email",
  validationContactPerson: "Must be 30 characters or less",
  validationDailyLimitMin: "Daily limit should be minimum 9,999",
  validationDailyLimitMax: "Daily limit should not exceed 999,999,999",
  validationOfficePhoneNumber: "Office Number is not valid",
  officeNumberValidate: "Office Number not valid",
  validationMobileNumber: "Mobile number is not valid",
  validationAddAccountNumber: "Invalid IBAN / Account Number",
  validationSwift: "Invalid SWIFT",

  selectMultipleService: "You can select multiple services per module.",
  mothersMaidenName: "Mothers Maiden Name",
  addAccount: "Add Account",
  AccountsCardsAccess: "Accounts/Cards Access",
  AccountsCardsAccessDesc:
    "Select the services required to be accessible under each account",
  modules: "Modules",
  noUsersAdded: "No Users Added",
  corporateUserDetails: "Corporate User Details",
  userAccess: "User Access",
  iban: "IBAN",
  userId: "User ID",
  firstName: "First Name *",
  userGroup: "User Group",
  lastName: "Last Name *",
  email: "Email *",
  location: "Location",
  saveAndAdd: "Save & Add More",
  eidOrPassportNumber: "Emirates ID / Passport No. *",
  dateOfBirth: "Date Of Birth",
  corporateDetailsDesc:
    "Click on + button to add the User details to be on-boarded.",
  userSummaryDesc:
    "Click on + button to add the User details to be on-boarded.",
  paymentsNote:
    "Note: Payments include Transfer within FAB, Bill Payment, Domestic Fund Transfer and International Fund Transfer",
  accountAlreadyExists: "Account already exists",
  corporateDetails: "Corporate Details",
  userSummary: "User Summary",
  moduleSettings: "Module Settings",
  specialInstructions: "Special Instructions",
  authorisation: "Authorisation",
  summary: "Summary",
  selectAll: "Select All",
  addUser: "Add User",
  accountsEmpty: "Add atleast one account",
  rolesEmpty: "Add atleast one role",
  userIdBetween8To16: "User ID should be between 8 to 16 characters",
  fieldRequired: "This field is required",
  welcomeTitle: "Welcome",
  accountList: "Account List",
  collapseAll: "Collapse All",
  expandAll: "Expand All",
  firstYouNeedToAccept:
    "First, you need accept the terms and conditions of the service.",
  checkYourMobile: "Check your mobile ({0})",
  asWeHaveSentYou: "as we have sent you a verification code",
  verifcationCodeValidity: "Your verification code is valid for {0} {1}",
  didntRecieveOTP: "Didn’t recieve a verification code? ",
  resendOTP: "Resend OTP",
  accountsNote:
    "By default Non-FAB accounts will have access to Account Services.",
  userIDFieldNote: "Preferred User ID (between 8 to 16 characters)",
  addUserAccessError:
    "One of the accounts you added is already added for {0} module and {1} role",
  editUser: "Save User",
  userAccessRequired: "You have to atleast add one user access permission",
  uploadDocuments: "Upload Documents",
  authorizationLimits: "Authorization Limits",
  approvalAndAuthorisation: "Approval & Authorisation",
  min: "Min",
  max: "Max",
  uploadFile: "Upload File",
  validationLimit: "Limit Should Be between 1 - 500,000",
  authRuleDesc: "2A + 1B (2 approver from Group A and 1 approval from Group B)",
  moduleSettingsDesc: "Set the details for each module.",
  empMolName: "Employer / MOL Registered Name",
  empMolId: "Employer ID / MOL ID",
  notificationEmailId: "Notification Email ID",
  productCode: "Product Code",
  notificationEmail: "Notification Email",
  companyCode: "Company Code",
  minChequeAmount: "Min. Cheque Amount",
  maxChequeAmount: "Max. Cheque Amount",
  averageNumberofCheques: "Average Number of Cheques",
  postDatedChequesRequired: "Post Dated Cheques Required",
  paramters: "Paramters",
  chequeDeliveryOptions: "Cheque Delivery Options",
  courierToBeArrangedFab: "Courier to be arranged by FAB",
  courierToBeArrangedCustomer: "Courier to be arranged by the Customer",
  RcdFollowingAccount: "RCD Access Required for Following Account",
  rcdAccountNumber: "Enter the Account Number",
  feesAndCharges: "Fees and Charges",
  feesAndChargesDesc:
    "The Customer will be charged in bulk for all services as agreed in this Schedule of Fees and Charges.",
  cutOfTimings: "Cut-Off Timings for Delivery of Cheques",
  cutOfTimingsDesc1: `1. Cut-off time of scanning the cheques for same day credit - 10:15hrs (on UAE Business Days, except public holidays).`,
  cutOfTimingsDesc2:
    "2. Cut-off time for delivery of scanned cheques to FAB's premises for same day credit - within 48 hours from cheque settlement date.",
  cutOfTimingsDesc3:
    "3. Cut-off time for delivery of scanned post-dated cheques (PDCs) to FAB's premises for lodgement and future processing on maturity date - within 48 hours from cheque scanning and transmission date.`",
  feeType: "Fee Type",
  chargeAccount: "Charge Account",
  frequency: "Frequency",
  debitAccountNumber: "Debit Account Number for Charges",
  setupFee: "Setup Fee",
  monthlyFee: "Monthly Fee",
  scannerFee: "Scanner Fee",
  pdcLodgementFee: "PDC Lodgement Fee",
  pdcWithdrawalFee: "PDC Withdrawal Fee",
  specialInstructionsDesc: "You can provide additional instructions.",
  billingInstructions: "Billing Instructions",
  billingInstructionsDesc:
    "Debit Account Number for Monthly Electronic Banking Fee",
  authorization: "Authorization",
  authorizationDesc:
    "First, you need accept the terms and conditions of the service.",
  conditionsNote:
    "These conditions have been executed by (or on behalf of) the Customer on",
  customerName: "Customer Name",
  title: "Title",
  forAndOnBehalfof: "For and on behalf of",
  asTheCustomer: "(as the customer)",
  date: "Date",
  signatories: "Signatories",
  customer: "Customer",
  authRuleFirst: ` I/We, duly authorised signatory of {0} hereby declare that the information given above is true and correct and it does not conflict or contradict any of and is otherwise in compliance with our constitutional documents and corporate authorization(s) relating to this application, the services or any related action subject of this application. I/We certify that:`,
  authRuleSecond: `I/We have received a copy of the corporate Electronic Banking Services Conditions contained in the Schedule to this application (the “Conditions”). I/ We confirm that I we have fully read and understood the Conditions and am/are duly authorised on behalf of {0} to agree that {1} shall be bound by the Conditions. In addition, I/we acknowledge and agree that the pricing applicable to this service may vary from time to time.`,
  authRuleThird: `I/We hereby acknowledge that I/We have received the RSA token(s) with the serial number(s) noted in section E (Corporate User Details & Access) of this application.`,
  authRuleCertify: ` I/We certify that:\nI. On or before the date of this application, I/We have delivered to First Abu Dhabi Bank PJSC a correct and complete copy of the constitutional documents of {0} , which, as of the date of this application, are upto-date;\n and
  II.{1} has taken all necessary steps to approve the terms of and thetransactions contemplated by this application and/or the services or any related action subject of this application.`,
  authRuleFourth: ` I/We hereby acknowledge that I/We have received the RSA token(s) with the serial number(s) noted in section E (Corporate User Details & Access) of this application.`,
  summaryDesc: "Review what you have so far.",
  accountsCardsAccess: "Accounts Cards Access",
  transactionAuthorizationRules: "Transaction Authorization Rules",
  corporateDailyLimit: "Corporate Daily Limit",
  appSubmitted: "Congratulations your application has been submited",
  yourRefId: " Your Reference ID {0} ",
  next: "Next",
  exporttoPDF: "Export to PDF",
  warning: "Warning",
  ok: "Ok",
  no: "No",
  yes: "Yes",
  oicRegNumber: "Enter OIC Registration Account",
  accountsAlertMessage: "We need at least one account to continue",
  endOfDayFileandAck: "End of Day File & ACK/NACK:",
  swift101Title: "SWIFT MT101",
};

export default en;
